version: '3.8'

services:

  # dbt-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: [ "dbt-rpc", "serve" ]
  #   env_file: .env
  #   environment:
  #     - DBT_ENABLE_LEGACY_LOGGER=True
  #   ports:
  #     - '8581:8580'
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - default

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}:${BUILD_VERSION}
    container_name: ${DOCKER_CONTAINER_NAME}
    command: [ "/bin/bash" ]
    stdin_open: true
    env_file: .env
    volumes:
      - ${DBT_PROJECT_FOLDER}/:/usr/src/dbt
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
