#version: '3.8'

services:

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}:${BUILD_VERSION}
    container_name: ${DOCKER_CONTAINER_NAME}
    command: [ "/bin/bash" ]
    ports:
      - "${DBT_DOCS_PORT}:8080"
    stdin_open: true
    env_file: .env
    volumes:
      - ${DBT_PROJECT}:/usr/src/dbt
      - ${DBT_PROFILES}:/root/.dbt/profiles.yml
      #- /etc/ssl:/usr/local/share/ca-certificates
    tty: true
    networks:
      - default

#networks:
#  default:
#    driver: bridge
