config:
  send_anonymous_usage_stats: False
  use_colors: True

databricks_dev:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ env_var('DB_CATALOG') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      host: "{{ env_var('DB_HOST') }}"
      http_path: "{{ env_var('DB_HTTP_PATH') }}"
      token: "{{ env_var('DB_TOKEN') }}" # Personal Access Token (PAT)
      threads: "{{ env_var('DB_THREADS') }}"  # optional, default 1